# Generated by Django 4.2.1 on 2023-06-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
