# Generated by Django 4.2.1 on 2023-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_product_blocked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="blocked",
        ),
        migrations.AddField(
            model_name="user",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
